name: Test Backend on Push

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - '*' 
      - '!main'
    paths:
      - 'linktreeclone-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./linktreeclone-backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Maven Tests
        run: mvn clean verify