name: Test Frontend on Push

on:
  push:
    branches:
      - '*'      # Roda em qualquer branch
      - '!main'  # Exceto na main
    paths:
      - 'linktreeclone-frontend/**'
jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./linktreeclone-frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'       

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test